-- local mocha = require("catppuccin.palettes").get_palette "mocha"
-- require("bufferline").setup{
--     options = {
--         show_buffer_close_icons = false,
--         offsets = {
--         },
--         color_icons = true, -- whether or not to add the filetype icon highlights
--         get_element_icon = function(element)
--           -- element consists of {filetype: string, path: string, extension: string, directory: string}
--           -- This can be used to change how bufferline fetches the icon
--           -- for an element e.g. a buffer or a tab.
--           -- e.g.
--           local icon, hl = require('nvim-web-devicons').get_icon_by_filetype(element.filetype, { default = false })
--           return icon, hl
--         end,
--     },
--     highlights = require("catppuccin.groups.integrations.bufferline").get {
--         styles = { "italic", "bold" },
--     },
-- }
